# config_PY.yml
# Ejemplo de configuración para correr el pipeline con tu fork.
# Ajusta rutas según tu repo. El pipeline debería:
# 1) expandir abreviaturas,
# 2) detectar conceptos por diccionario,
# 3) aplicar reglas de contexto para rotular (affirmed/negated/historical/family/hypothetical),
# 4) exportar un CSV de features por documento/paciente.

language: es
concepts_file: "resources/concepts_PY.yml"
context_rules_file: "resources/context_rules_PY.yml"

matching:
  case_sensitive: false
  use_word_boundaries: true
  normalize_accents: true
  min_token_len: 2

context:
  apply_negation: true
  apply_uncertainty: true
  apply_historical: true
  apply_family: true
  apply_hypothetical: true
  apply_severity: true
  apply_temporality: true

features:
  aggregate_level: "patient"      # "document" o "patient"
  counts:
    affirmed: true
    negated: true
    historical: true
    family: true
    hypothetical: true
  severity_bucket: true           # leve/moderado/grave si disponible
  recency_window_days: 90         # para features "reciente"

output:
  features_csv: "outputs/features_PY.csv"
  hits_jsonl:  "outputs/hits_PY.jsonl"   # trazabilidad de ocurrencias

logging:
  level: "INFO"
  sample_examples: true
